# Generated by Django 5.1.7 on 2026-03-18 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(help_text='Уникальный позывной, используется для входа', max_length=50, unique=True, verbose_name='Логин (позывной)')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Номер в формате +7XXXXXXXXXX', max_length=20, unique=True, verbose_name='Телефон')),
                ('rank', models.CharField(blank=True, max_length=100, verbose_name='Звание')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('unit', models.CharField(blank=True, max_length=200, verbose_name='Подразделение')),
                ('role', models.CharField(choices=[('cadet', 'Курсант'), ('commander', 'Командир'), ('instructor', 'Инструктор'), ('qa', 'QA'), ('admin', 'Admin'), ('curator', 'Куратор')], default='cadet', max_length=20, verbose_name='Роль')),
                ('voevoda_index', models.FloatField(default=0.0, verbose_name='Индекс Воеводы')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал (доступ в админку)')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['login'], name='users_user_login_2e7f80_idx'), models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'), models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx')],
            },
        ),
    ]
